name: Checks

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  lint:
    runs-on: namespace-profile-linux-default

    steps:
      - name: Checkout repository
        uses: namespacelabs/nscloud-checkout-action@9

      - name: Set up cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          cache: "bun"

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run linter
        run: bun run check:all
